### ISSUE TITLE
references to string.js in the readme but the file in the repo is index.js

### ISSUE THREAD

**Issue by deniznida** [learn-co-students/javascript-strings-lab-js-intro-000#8]

**Comment by deniznida** [comment]
wasn't sure if you were getting email notifications for opened issues :)

**Comment by pletcher** [comment]
Oops! My bad

**Comment by pletcher** [comment]
Fixed via https://github.com/learn-co-curriculum/javascript-strings-lab/commit/c2c25f5455cc76c241c750ddbd93cb1a450f5f2c

**Comment by deniznida** [comment]
thanks, @pletcher that was quick :)
